#include <iostream>
#include <string>
#define string std::string



int main(){
    // const array are immutable
    // const int mutiplier[] {123, 100};
    // mutiplier[2] = 20;

    // string arr[] = {"fdsa", "fdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewqfdeqrewq", "fweqrewqrewq", "fewqfewqfewq"};

    // std::cout << "entire size of string array : " << sizeof(arr) << std::endl;
    // std::cout << "size of first array size : " << sizeof(arr[0]) << std::endl;
    // std::cout << "size of second array size : " << sizeof(arr[1]) << std::endl;
    // std::cout << "number of element : " << sizeof(arr) / sizeof(arr[0]) << std::endl;


    // const char* charArr = {"hello world"};
    // std::cout << "entire size of string array : " << std::endl;



    // 
    //   
    //
    // int *p_number; // Contain junk address : could be anything
    // *p_number = 55; // Writing into junk address: BAD!
    // std::cout << std::endl;
    // std::cout << "Writing into uninitialized pointer through dereference " << std::endl;
    // std::cout << "p_number " << p_number << std::endl; // Reading from junk address
    // std::cout << "*p_number " << *p_number << std::endl;


    // Use dynamic heap memory instead of stack memory
    int *p_number{nullptr};
    p_number = new int;
    *p_number = 55;
    std::cout << "Dynamically allocated memory " << std::endl;
    std::cout << "*p_number " << p_number << std::endl;
    std::cout << "p_number " << *p_number << std::endl;

    delete p_number;
    p_number = nullptr;
    std::cout << "Writing in bad memory " << std::endl;
    *p_number = 45;
    std::cout << "Done writing! " << *p_number << std::endl;

    
    return 0;
}